// CodeInsight AI — AI Provider presets
// 14 supported providers, each with its catalog of models & default base URL.

import type { ProviderPreset, ProviderId } from "./types";

export const PROVIDER_PRESETS: ProviderPreset[] = [
  {
    providerId: "openrouter",
    name: "OpenRouter",
    category: "Aggregator",
    defaultBaseUrl: "https://openrouter.ai/api/v1",
    docsUrl: "https://openrouter.ai/keys",
    defaultModel: "anthropic/claude-3.5-sonnet",
    models: [
      "anthropic/claude-3.5-sonnet",
      "anthropic/claude-3.7-sonnet",
      "openai/gpt-4o",
      "openai/gpt-4o-mini",
      "google/gemini-pro-1.5",
      "deepseek/deepseek-chat",
      "meta-llama/llama-3.1-70b-instruct",
      "qwen/qwen-2.5-72b-instruct",
      "mistralai/mistral-large",
    ],
    requiresKey: true,
    accent: "#8b5cf6",
    local: false,
  },
  {
    providerId: "openai",
    name: "OpenAI",
    category: "Cloud",
    defaultBaseUrl: "https://api.openai.com/v1",
    docsUrl: "https://platform.openai.com/api-keys",
    defaultModel: "gpt-4o",
    models: ["gpt-4o", "gpt-4o-mini", "gpt-4-turbo", "gpt-3.5-turbo", "o1-preview", "o1-mini"],
    requiresKey: true,
    accent: "#10a37f",
    local: false,
  },
  {
    providerId: "anthropic",
    name: "Anthropic (Claude)",
    category: "Cloud",
    defaultBaseUrl: "https://api.anthropic.com/v1",
    docsUrl: "https://console.anthropic.com/settings/keys",
    defaultModel: "claude-3-5-sonnet-20241022",
    models: ["claude-3-5-sonnet-20241022", "claude-3-5-haiku-20241022", "claude-3-opus-20240229"],
    requiresKey: true,
    accent: "#d97706",
    local: false,
  },
  {
    providerId: "gemini",
    name: "Google Gemini",
    category: "Cloud",
    defaultBaseUrl: "https://generativelanguage.googleapis.com/v1beta",
    docsUrl: "https://aistudio.google.com/app/apikey",
    defaultModel: "gemini-1.5-pro",
    models: ["gemini-1.5-pro", "gemini-1.5-flash", "gemini-2.0-flash-exp"],
    requiresKey: true,
    accent: "#4285f4",
    local: false,
  },
  {
    providerId: "deepseek",
    name: "DeepSeek",
    category: "Cloud",
    defaultBaseUrl: "https://api.deepseek.com/v1",
    docsUrl: "https://platform.deepseek.com/api_keys",
    defaultModel: "deepseek-chat",
    models: ["deepseek-chat", "deepseek-coder", "deepseek-reasoner"],
    requiresKey: true,
    accent: "#4d6bfe",
    local: false,
  },
  {
    providerId: "groq",
    name: "Groq",
    category: "Cloud · Fast",
    defaultBaseUrl: "https://api.groq.com/openai/v1",
    docsUrl: "https://console.groq.com/keys",
    defaultModel: "llama-3.3-70b-versatile",
    models: ["llama-3.3-70b-versatile", "llama-3.1-8b-instant", "mixtral-8x7b-32768", "gemma2-9b-it"],
    requiresKey: true,
    accent: "#f55036",
    local: false,
  },
  {
    providerId: "ollama",
    name: "Ollama",
    category: "Local",
    defaultBaseUrl: "http://localhost:11434/v1",
    docsUrl: "https://ollama.com/download",
    defaultModel: "llama3.2",
    models: ["llama3.2", "llama3.1", "qwen2.5", "deepseek-r1", "mistral", "phi3", "gemma2"],
    requiresKey: false,
    accent: "#22d3ee",
    local: true,
  },
  {
    providerId: "lmstudio",
    name: "LM Studio",
    category: "Local",
    defaultBaseUrl: "http://localhost:1234/v1",
    docsUrl: "https://lmstudio.ai",
    defaultModel: "local-model",
    models: ["local-model"],
    requiresKey: false,
    accent: "#34d399",
    local: true,
  },
  {
    providerId: "azure",
    name: "Azure OpenAI",
    category: "Enterprise",
    defaultBaseUrl: "https://YOUR-RESOURCE.openai.azure.com/openai/deployments",
    docsUrl: "https://learn.microsoft.com/azure/ai-services/openai",
    defaultModel: "gpt-4o",
    models: ["gpt-4o", "gpt-4o-mini", "gpt-35-turbo", "o1", "o3-mini"],
    requiresKey: true,
    accent: "#0078d4",
    local: false,
  },
  {
    providerId: "together",
    name: "Together AI",
    category: "Cloud",
    defaultBaseUrl: "https://api.together.xyz/v1",
    docsUrl: "https://api.together.ai/settings/api-keys",
    defaultModel: "meta-llama/Llama-3.3-70B-Instruct-Turbo",
    models: ["meta-llama/Llama-3.3-70B-Instruct-Turbo", "Qwen/Qwen2.5-72B-Instruct-Turbo", "deepseek-ai/DeepSeek-V3"],
    requiresKey: true,
    accent: "#0f6fff",
    local: false,
  },
  {
    providerId: "fireworks",
    name: "Fireworks AI",
    category: "Cloud",
    defaultBaseUrl: "https://api.fireworks.ai/inference/v1",
    docsUrl: "https://fireworks.ai/account/api-keys",
    defaultModel: "accounts/fireworks/models/llama-v3p3-70b-instruct",
    models: ["accounts/fireworks/models/llama-v3p3-70b-instruct", "accounts/fireworks/models/qwen2p5-72b-instruct"],
    requiresKey: true,
    accent: "#ff6b35",
    local: false,
  },
  {
    providerId: "mistral",
    name: "Mistral",
    category: "Cloud",
    defaultBaseUrl: "https://api.mistral.ai/v1",
    docsUrl: "https://console.mistral.ai/api-keys",
    defaultModel: "mistral-large-latest",
    models: ["mistral-large-latest", "mistral-small-latest", "codestral-latest", "open-mixtral-8x7b"],
    requiresKey: true,
    accent: "#ff7000",
    local: false,
  },
  {
    providerId: "xai",
    name: "xAI (Grok)",
    category: "Cloud",
    defaultBaseUrl: "https://api.x.ai/v1",
    docsUrl: "https://console.x.ai",
    defaultModel: "grok-2-latest",
    models: ["grok-2-latest", "grok-2-mini", "grok-beta"],
    requiresKey: true,
    accent: "#1d9bf0",
    local: false,
  },
  {
    providerId: "shopaikey",
    name: "ShopAIKey (Marketplace)",
    category: "Aggregator",
    defaultBaseUrl: "https://api.shopaikey.com/v1",
    docsUrl: "https://shopaikey.com/en/docs/introduction",
    defaultModel: "gpt-4.1-mini",
    models: [
      "gpt-5-nano",
      "gpt-4.1-nano",
      "gpt-4o-mini",
      "gpt-5-mini",
      "gpt-4.1-mini",
      "grok-4-fast-reasoning",
      "deepseek-chat",
      "qwen3-coder-flash",
    ],
    modelInfo: [
      { id: "gpt-5-nano", useCase: "budget", badge: "Cheapest · Free default ($0.05/$0.40)", maxTokens: 1000 },
      { id: "gpt-4.1-nano", useCase: "fast", badge: "Fast · Low cost ($0.10/$0.40)", maxTokens: 1500 },
      { id: "gpt-4o-mini", useCase: "vision", badge: "Vision · Multimodal ($0.15/$0.60)", maxTokens: 2000 },
      { id: "gpt-5-mini", useCase: "chat", badge: "Best for Chat ($0.25/$2.00)", maxTokens: 3000 },
      { id: "gpt-4.1-mini", useCase: "analyze", badge: "Best for Analyze ($0.40/$1.60)", maxTokens: 4000 },
      { id: "grok-4-fast-reasoning", useCase: "fast", badge: "Fast Reasoning ($0.20/$0.50)", maxTokens: 2000 },
      { id: "deepseek-chat", useCase: "code", badge: "Best for Code ($2.00/$3.00)", maxTokens: 3000 },
      { id: "qwen3-coder-flash", useCase: "code", badge: "Code Specialist ($1.00/$4.00)", maxTokens: 3000 },
    ],
    requiresKey: true,
    accent: "#10b981",
    local: false,
  },
  {
    providerId: "custom",
    name: "Custom (OpenAI-compatible)",
    category: "Custom",
    defaultBaseUrl: "http://localhost:8080/v1",
    docsUrl: "",
    defaultModel: "custom-model",
    models: ["custom-model"],
    requiresKey: false,
    accent: "#a78bfa",
    local: false,
  },
];

export const PRESET_BY_ID = Object.fromEntries(
  PROVIDER_PRESETS.map((p) => [p.providerId, p])
) as Record<string, ProviderPreset>;

export const FEATURE_LABELS: Record<string, string> = {
  chat: "Repository Chat",
  bugs: "Bug Detection",
  security: "Security Analysis",
  performance: "Performance Analysis",
  architecture: "Architecture Review",
  docs: "Documentation",
  vision: "Vision / Images",
  refactor: "Refactoring",
  summary: "Repository Summary",
};

// Suggested default provider per feature (user can override).
export const FEATURE_DEFAULTS: Record<string, ProviderId> = {
  chat: "openai",
  bugs: "anthropic",
  security: "anthropic",
  performance: "deepseek",
  architecture: "anthropic",
  docs: "deepseek",
  vision: "gemini",
  refactor: "openrouter",
  summary: "openai",
};
