---
name: Feature Request
about: Suggest an idea for this project
title: "[FEATURE] "
labels: enhancement
---

**Is your feature request related to a problem?**
A clear description of the problem.

**Proposed solution**
What you'd like to see.

**Alternatives considered**
Any alternative solutions.

**Additional context**
Any other context or screenshots.
