// CodeInsight AI — DevOps Agent (Prompt 11)
// Generates DevOps & deployment configuration files: Dockerfile, docker-compose,
// nginx, GitHub Actions CI, Vercel/Railway/Render/Fly/Coolify, Kubernetes manifest.
// Extends BaseAgent so it slots into the multi-agent system; also exports a
// standalone `generateDevOpsConfig` helper for direct use.

import type {
  AgentInfo,
  Task,
  TaskArtifact,
  TaskResult,
} from "./types";
import { BaseAgent } from "./base-agent";
import {
  callAIForJSON,
  type AIProviderConfig,
} from "./ai-client";

// ────────────────────────────────────────────────────────────────────────────
// Types
// ────────────────────────────────────────────────────────────────────────────

export type DevOpsOperation =
  | "dockerize"
  | "compose"
  | "nginx"
  | "ci-github-actions"
  | "deploy-vercel"
  | "deploy-railway"
  | "deploy-render"
  | "deploy-fly"
  | "deploy-coolify"
  | "kubernetes-manifest";

export interface ProjectInfo {
  name: string;
  framework?: string;
  language?: string;
  packageManager?: string;
  entrypoint?: string;
  port?: number;
}

export interface DevOpsConfigResult {
  operation: DevOpsOperation;
  path: string;
  language: string;
  content: string;
  meta: Record<string, unknown>;
}

export interface DevOpsConfigInput {
  operation: DevOpsOperation;
  projectInfo: ProjectInfo;
  provider?: AIProviderConfig;
}

// Maps each operation to its primary output filename + artifact language hint.
const OPERATION_META: Record<
  DevOpsOperation,
  { path: string; language: string; label: string }
> = {
  dockerize: { path: "Dockerfile", language: "dockerfile", label: "Dockerfile" },
  compose: {
    path: "docker-compose.yml",
    language: "yaml",
    label: "docker-compose.yml",
  },
  nginx: { path: "nginx.conf", language: "nginx", label: "nginx.conf" },
  "ci-github-actions": {
    path: ".github/workflows/ci.yml",
    language: "yaml",
    label: "GitHub Actions CI",
  },
  "deploy-vercel": { path: "vercel.json", language: "json", label: "Vercel Config" },
  "deploy-railway": {
    path: "railway.json",
    language: "json",
    label: "Railway Config",
  },
  "deploy-render": { path: "render.yaml", language: "yaml", label: "Render Config" },
  "deploy-fly": { path: "fly.toml", language: "toml", label: "Fly.io Config" },
  "deploy-coolify": {
    path: "coolify.yaml",
    language: "yaml",
    label: "Coolify Config",
  },
  "kubernetes-manifest": {
    path: "k8s.yaml",
    language: "yaml",
    label: "Kubernetes Manifest",
  },
};

// ────────────────────────────────────────────────────────────────────────────
// Template generators — each returns the raw file content for the operation.
// ────────────────────────────────────────────────────────────────────────────

function detectBaseImage(language: string, framework?: string): string {
  const lang = language.toLowerCase();
  const fw = (framework ?? "").toLowerCase();
  if (lang === "typescript" || lang === "javascript") {
    if (fw === "nextjs" || fw === "next.js") return "node:20-alpine";
    return "node:20-alpine";
  }
  if (lang === "python") {
    if (fw === "django") return "python:3.11-slim";
    return "python:3.11-slim";
  }
  if (lang === "go") return "golang:1.21-alpine";
  if (lang === "rust") return "rust:1.75";
  if (lang === "java") return "eclipse-temurin:21-jdk-alpine";
  if (lang === "ruby") return "ruby:3.2-slim";
  if (lang === "php") return "php:8.2-fpm-alpine";
  return "node:20-alpine";
}

function detectPackageCmd(packageManager: string | undefined): {
  install: string;
  build: string;
  start: string;
  lockfile: string;
} {
  switch ((packageManager ?? "npm").toLowerCase()) {
    case "yarn":
      return {
        install: "yarn install --frozen-lockfile",
        build: "yarn build",
        start: "yarn start",
        lockfile: "yarn.lock",
      };
    case "pnpm":
      return {
        install: "pnpm install --frozen-lockfile",
        build: "pnpm build",
        start: "pnpm start",
        lockfile: "pnpm-lock.yaml",
      };
    case "bun":
      return {
        install: "bun install --frozen-lockfile",
        build: "bun run build",
        start: "bun run start",
        lockfile: "bun.lockb",
      };
    case "npm":
    default:
      return {
        install: "npm ci",
        build: "npm run build",
        start: "npm start",
        lockfile: "package-lock.json",
      };
  }
}

/** Next.js standalone build Dockerfile — multi-stage, non-root, minimal image. */
function dockerfileNextJs(p: ProjectInfo): string {
  const pkg = detectPackageCmd(p.packageManager);
  const port = p.port ?? 3000;
  return `# Multi-stage Dockerfile for Next.js — ${p.name}
# Generated by CodeInsight AI DevOps Agent

# ── deps ───────────────────────────────────────────────────────────────────
FROM node:20-alpine AS deps
WORKDIR /app
COPY package*.json ${pkg.lockfile} ./
RUN ${pkg.install}

# ── builder ─────────────────────────────────────────────────────────────────
FROM node:20-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
ENV NEXT_TELEMETRY_DISABLED=1
RUN ${pkg.build}

# ── runner ──────────────────────────────────────────────────────────────────
FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
RUN addgroup -g 1001 -S nodejs && adduser -S nextjs -u 1001
COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
USER nextjs
EXPOSE ${port}
ENV PORT=${port}
ENV HOSTNAME="0.0.0.0"
CMD ["node", "server.js"]
`;
}

/** Generic Node.js Dockerfile. */
function dockerfileNodeJs(p: ProjectInfo): string {
  const pkg = detectPackageCmd(p.packageManager);
  const port = p.port ?? 3000;
  return `# Dockerfile for Node.js — ${p.name}
FROM node:20-alpine
WORKDIR /app
COPY package*.json ${pkg.lockfile} ./
RUN ${pkg.install}
COPY . .
RUN ${pkg.build}
ENV NODE_ENV=production
EXPOSE ${port}
CMD ["sh", "-c", "${pkg.start}"]
`;
}

function dockerfilePython(p: ProjectInfo): string {
  const framework = (p.framework ?? "").toLowerCase();
  const entrypoint = p.entrypoint ?? "main:app";
  const port = p.port ?? 8000;
  const startCmd =
    framework === "django"
      ? `gunicorn ${entrypoint.split(":")[0] || "myproject"}.wsgi:application --bind 0.0.0.0:${port}`
      : `uvicorn ${entrypoint}:app --host 0.0.0.0 --port ${port}`;
  return `# Dockerfile for Python — ${p.name}
FROM python:3.11-slim
WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE ${port}
CMD ["sh", "-c", "${startCmd}"]
`;
}

function dockerfileGo(p: ProjectInfo): string {
  const port = p.port ?? 8080;
  return `# Multi-stage Dockerfile for Go — ${p.name}
FROM golang:1.21-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o /server .

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /server .
EXPOSE ${port}
CMD ["./server"]
`;
}

function dockerfileRust(p: ProjectInfo): string {
  const port = p.port ?? 8080;
  const binName = p.name || "app";
  return `# Multi-stage Dockerfile for Rust — ${p.name}
FROM rust:1.75 AS builder
WORKDIR /app
COPY Cargo.toml Cargo.lock ./
RUN mkdir src && echo "fn main() {}" > src/main.rs && cargo build --release && rm -rf src
COPY src ./src
RUN cargo build --release

FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY --from=builder /app/target/release/${binName} ./
EXPOSE ${port}
CMD ["./${binName}"]
`;
}

function dockerfileJava(p: ProjectInfo): string {
  const port = p.port ?? 8080;
  return `# Multi-stage Dockerfile for Java — ${p.name}
FROM maven:3.9-eclipse-temurin-21 AS builder
WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline
COPY src ./src
RUN mvn package -DskipTests

FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY --from=builder /app/target/*.jar app.jar
EXPOSE ${port}
CMD ["java", "-jar", "app.jar"]
`;
}

function dockerfileGeneric(p: ProjectInfo): string {
  // Fallback — pick a sane base image and document assumptions.
  const baseImage = detectBaseImage(p.language ?? "node", p.framework);
  return `# Generic Dockerfile for ${p.name} (language: ${p.language ?? "unknown"})
FROM ${baseImage}
WORKDIR /app
COPY . .
# TODO: Add language-specific build + run commands.
EXPOSE ${p.port ?? 3000}
CMD ["echo", "Configure start command for your application"]
`;
}

function buildDockerfile(p: ProjectInfo): string {
  const lang = (p.language ?? "").toLowerCase();
  const fw = (p.framework ?? "").toLowerCase();
  if (fw === "nextjs" || fw === "next.js") return dockerfileNextJs(p);
  if (lang === "typescript" || lang === "javascript") return dockerfileNodeJs(p);
  if (lang === "python") return dockerfilePython(p);
  if (lang === "go") return dockerfileGo(p);
  if (lang === "rust") return dockerfileRust(p);
  if (lang === "java") return dockerfileJava(p);
  return dockerfileGeneric(p);
}

/** docker-compose.yml — app + Postgres + Redis, common for full-stack apps. */
function buildDockerCompose(p: ProjectInfo): string {
  const port = p.port ?? 3000;
  const appName = (p.name || "app").toLowerCase().replace(/[^a-z0-9-]/g, "-");
  return `# docker-compose.yml — ${p.name}
# Generated by CodeInsight AI DevOps Agent
# Usage: docker compose up -d --build

version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${appName}
    ports:
      - "${port}:${port}"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:postgres@db:5432/appdb
      - REDIS_URL=redis://redis:6379
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: ${appName}-db
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: ${appName}-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  db_data:
  redis_data:
`;
}

/** nginx reverse-proxy config — terminates TLS, forwards to app. */
function buildNginx(p: ProjectInfo): string {
  const port = p.port ?? 3000;
  return `# nginx.conf — reverse proxy for ${p.name}
# Generated by CodeInsight AI DevOps Agent
# Forward requests to the app container on port ${port}.

upstream app_backend {
    server app:${port};
    keepalive 32;
}

server {
    listen 80;
    server_name _;

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    # Gzip
    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_types
        text/plain
        text/css
        application/json
        application/javascript
        text/xml
        application/xml
        application/xml+rss
        text/javascript;

    client_max_body_size 10M;

    location / {
        proxy_pass http://app_backend;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \\$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \\$host;
        proxy_set_header X-Real-IP \\$remote_addr;
        proxy_set_header X-Forwarded-For \\$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \\$scheme;
        proxy_cache_bypass \\$http_upgrade;
        proxy_read_timeout 60s;
    }

    # Cache static assets aggressively
    location ~* \\.(?:ico|css|js|woff2?|ttf|otf|eot|svg|png|jpg|jpeg|gif|webp)$ {
        proxy_pass http://app_backend;
        proxy_cache_valid 200 1h;
        expires 1h;
        add_header Cache-Control "public, max-age=3600";
    }

    # Health check endpoint
    location = /health {
        access_log off;
        return 200 "ok\\n";
        add_header Content-Type text/plain;
    }
}
`;
}

/** GitHub Actions CI workflow. */
function buildGitHubActionsCI(p: ProjectInfo): string {
  const pkg = detectPackageCmd(p.packageManager);
  const lang = (p.language ?? "").toLowerCase();
  const fw = (p.framework ?? "").toLowerCase();

  // Python path
  if (lang === "python") {
    return `# .github/workflows/ci.yml — CI for ${p.name}
name: CI
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python \${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: \${{ matrix.python-version }}
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff mypy pytest
      - name: Lint (ruff)
        run: ruff check .
      - name: Type-check (mypy)
        run: mypy .
      - name: Test (pytest)
        run: pytest --maxfail=1 --disable-warnings
`;
  }

  // Go path
  if (lang === "go") {
    return `# .github/workflows/ci.yml — CI for ${p.name}
name: CI
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          cache: true
      - name: Install
        run: go mod download
      - name: Vet
        run: go vet ./...
      - name: Test
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
      - name: Build
        run: go build ./...
`;
  }

  // Default: Node.js
  const setupNode = `      - name: Use Node.js \${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: \${{ matrix.node-version }}
          cache: "${pkg.install.startsWith("npm") ? "npm" : pkg.install.split(" ")[0]}"`;
  const installCmd = pkg.install.startsWith("npm")
    ? "npm ci"
    : pkg.install.startsWith("yarn")
      ? "yarn install --immutable"
      : pkg.install.startsWith("pnpm")
        ? "pnpm install --frozen-lockfile"
        : "bun install --frozen-lockfile";
  const lintCmd = pkg.install.startsWith("npm")
    ? "npm run lint --if-present"
    : `${pkg.install.split(" ")[0]} run lint --if-present`;
  const buildCmd = pkg.build;
  const testCmd = `${pkg.install.split(" ")[0] === "npm" ? "npm" : pkg.install.split(" ")[0]} test --if-present`;

  return `# .github/workflows/ci.yml — CI for ${p.name}
name: CI
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
${setupNode}
      - name: Install dependencies
        run: ${installCmd}
      - name: Lint
        run: ${lintCmd}
      - name: Build
        run: ${buildCmd}
      - name: Test
        run: ${testCmd}
${fw === "nextjs" || fw === "next.js" ? `
  build-docker:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: ${p.name.toLowerCase()}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
` : ""}`;
}

function buildVercelConfig(p: ProjectInfo): string {
  const fw = (p.framework ?? "").toLowerCase();
  const framework =
    fw === "nextjs" || fw === "next.js"
      ? "nextjs"
      : fw === "remix"
        ? "remix"
        : fw === "vite" || fw === "react"
          ? "vite"
          : "nextjs";
  const pkg = detectPackageCmd(p.packageManager);
  const installCmd =
    pkg.install.startsWith("npm") || pkg.install.startsWith("yarn") || pkg.install.startsWith("pnpm")
      ? `${pkg.install.split(" ")[0]} install`
      : "bun install";
  return `{
  "$schema": "https://openapi.vercel.sh/vercel.json",
  "framework": "${framework}",
  "buildCommand": "${pkg.build}",
  "installCommand": "${installCmd}",
  "outputDirectory": "${framework === "vite" ? "dist" : ".next"}",
  "regions": ["iad1"],
  "github": {
    "silent": true
  },
  "headers": [
    {
      "source": "/(.*)",
      "headers": [
        { "key": "X-Frame-Options", "value": "SAMEORIGIN" },
        { "key": "X-Content-Type-Options", "value": "nosniff" },
        { "key": "Referrer-Policy", "value": "strict-origin-when-cross-origin" }
      ]
    }
  ]
}
`;
}

function buildRailwayConfig(p: ProjectInfo): string {
  const pkg = detectPackageCmd(p.packageManager);
  return `{
  "$schema": "https://railway.app/railway.schema.json",
  "build": {
    "builder": "NIXPACKS",
    "buildCommand": "${pkg.build}"
  },
  "deploy": {
    "startCommand": "${pkg.start}",
    "restartPolicyType": "ON_FAILURE",
    "restartPolicyMaxRetries": 10,
    "healthcheckPath": "/api/health",
    "healthcheckTimeout": 30
  }
}
`;
}

function buildRenderConfig(p: ProjectInfo): string {
  const pkg = detectPackageCmd(p.packageManager);
  const lang = (p.language ?? "").toLowerCase();
  const runtime = lang === "python" ? "python" : "node";
  const buildCmd =
    runtime === "python"
      ? "pip install -r requirements.txt"
      : `${pkg.install} && ${pkg.build}`;
  const startCmd =
    runtime === "python"
      ? "uvicorn main:app --host 0.0.0.0 --port $PORT"
      : pkg.start;
  const port = p.port ?? 3000;
  return `# render.yaml — Render Blueprint for ${p.name}
# Generated by CodeInsight AI DevOps Agent

services:
  - type: web
    name: ${p.name}
    runtime: ${runtime}
    plan: free
    region: oregon
    buildCommand: ${buildCmd}
    startCommand: ${startCmd}
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "${port}"
    healthCheckPath: /api/health
    autoDeploy: true

  - type: postgres
    name: ${p.name}-db
    plan: free
    ipAllowList: []
`;
}

function buildFlyConfig(p: ProjectInfo): string {
  const port = p.port ?? 3000;
  const appName = (p.name || "app").toLowerCase().replace(/[^a-z0-9-]/g, "-");
  return `# fly.toml — Fly.io config for ${p.name}
# Generated by CodeInsight AI DevOps Agent
# Run: fly launch  (first time) or fly deploy

app = "${appName}"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "${port}"

[http_service]
  internal_port = ${port}
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 250

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[[http_service.checks]]
  interval = "30s"
  timeout = "5s"
  grace_period = "10s"
  method = "GET"
  path = "/api/health"
`;
}

function buildCoolifyConfig(p: ProjectInfo): string {
  const port = p.port ?? 3000;
  return `# coolify.yaml — Coolify deployment config for ${p.name}
# Generated by CodeInsight AI DevOps Agent
# Reference: https://coolify.io/docs/api-reference

service:
  name: ${p.name}
  type: application
  source:
    type: github
    repository: your-org/${p.name}
    branch: main
  build:
    pack: dockerfile
    dockerfile: Dockerfile
  ports:
    - port: ${port}
      protocol: http
  healthCheck:
    path: /api/health
    interval: 30
    timeout: 5
  environment:
    - key: NODE_ENV
      value: production
    - key: PORT
      value: "${port}"
  resources:
    cpu: 0.5
    memory: 512
  scaling:
    minReplicas: 1
    maxReplicas: 3
    targetCpu: 70
`;
}

function buildK8sManifest(p: ProjectInfo): string {
  const port = p.port ?? 3000;
  const appName = (p.name || "app").toLowerCase().replace(/[^a-z0-9-]/g, "-");
  const replicas = 3;
  return `# k8s.yaml — Kubernetes manifest for ${p.name}
# Generated by CodeInsight AI DevOps Agent
# Apply with: kubectl apply -f k8s.yaml

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${appName}
  labels:
    app: ${appName}
    tier: frontend
spec:
  replicas: ${replicas}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: ${appName}
  template:
    metadata:
      labels:
        app: ${appName}
        tier: frontend
    spec:
      containers:
        - name: ${appName}
          image: ${appName}:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: ${port}
              name: http
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "${port}"

---
apiVersion: v1
kind: Service
metadata:
  name: ${appName}
  labels:
    app: ${appName}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: ${appName}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${appName}-ingress
  labels:
    app: ${appName}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - ${appName}.example.com
      secretName: ${appName}-tls
  rules:
    - host: ${appName}.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ${appName}
                port:
                  number: 80

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ${appName}-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ${appName}
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
`;
}

// ────────────────────────────────────────────────────────────────────────────
// AI customization — if a provider is supplied, optionally enhance the
// generated config with project-specific tweaks (e.g., extra ENV vars,
// framework-aware optimizations). Falls back gracefully on AI failure.
// ────────────────────────────────────────────────────────────────────────────

interface AIEnhancement {
  notes?: string[];
  envVars?: Array<{ key: string; value: string }>;
  warnings?: string[];
}

async function aiEnhance(
  baseContent: string,
  operation: DevOpsOperation,
  projectInfo: ProjectInfo,
  provider: AIProviderConfig,
): Promise<AIEnhancement | null> {
  try {
    const systemMsg =
      "You are a senior DevOps engineer. Given a generated config file and project info, " +
      "return a JSON object with optional `notes` (string[]), `envVars` ({key,value}[]), and " +
      "`warnings` (string[]) to enhance the config. Keep it focused and minimal.";
    const userMsg = `Project: ${JSON.stringify(projectInfo)}\nOperation: ${operation}\n\nGenerated config:\n\n${baseContent.slice(0, 4000)}`;
    return await callAIForJSON<AIEnhancement>(provider, [
      { role: "system", content: systemMsg },
      { role: "user", content: userMsg },
    ]);
  } catch {
    return null;
  }
}

// ────────────────────────────────────────────────────────────────────────────
// Core helper — exported for direct use.
// ────────────────────────────────────────────────────────────────────────────

export async function generateDevOpsConfig(
  operation: DevOpsOperation,
  projectInfo: ProjectInfo,
  provider?: AIProviderConfig,
): Promise<DevOpsConfigResult> {
  // Validate
  if (!OPERATION_META[operation]) {
    throw new Error(`Unknown DevOps operation: ${operation}`);
  }
  if (!projectInfo || !projectInfo.name) {
    throw new Error("projectInfo.name is required");
  }

  const meta = OPERATION_META[operation];

  // Build base content from templates
  let content: string;
  switch (operation) {
    case "dockerize":
      content = buildDockerfile(projectInfo);
      break;
    case "compose":
      content = buildDockerCompose(projectInfo);
      break;
    case "nginx":
      content = buildNginx(projectInfo);
      break;
    case "ci-github-actions":
      content = buildGitHubActionsCI(projectInfo);
      break;
    case "deploy-vercel":
      content = buildVercelConfig(projectInfo);
      break;
    case "deploy-railway":
      content = buildRailwayConfig(projectInfo);
      break;
    case "deploy-render":
      content = buildRenderConfig(projectInfo);
      break;
    case "deploy-fly":
      content = buildFlyConfig(projectInfo);
      break;
    case "deploy-coolify":
      content = buildCoolifyConfig(projectInfo);
      break;
    case "kubernetes-manifest":
      content = buildK8sManifest(projectInfo);
      break;
    default:
      throw new Error(`Operation ${operation} has no template generator`);
  }

  // Optional AI enhancement
  const enhancement: AIEnhancement | null = provider
    ? await aiEnhance(content, operation, projectInfo, provider)
    : null;

  if (enhancement) {
    const banner = [
      enhancement.notes && enhancement.notes.length
        ? `# AI Notes:\n${enhancement.notes.map((n) => `#   - ${n}`).join("\n")}`
        : null,
      enhancement.warnings && enhancement.warnings.length
        ? `# AI Warnings:\n${enhancement.warnings.map((w) => `#   ! ${w}`).join("\n")}`
        : null,
    ]
      .filter(Boolean)
      .join("\n");

    if (banner && (meta.language === "yaml" || meta.language === "dockerfile" || meta.language === "toml")) {
      content = `${banner}\n${content}`;
    } else if (banner && meta.language === "json") {
      // For JSON, fold notes into a "_comment" field instead of a banner.
      try {
        const parsed = JSON.parse(content);
        parsed["_comment"] = (enhancement.notes ?? []).join("; ");
        content = JSON.stringify(parsed, null, 2) + "\n";
      } catch {
        // Leave content as-is if it isn't valid JSON.
      }
    }
  }

  return {
    operation,
    path: meta.path,
    language: meta.language,
    content,
    meta: {
      label: meta.label,
      projectInfo,
      enhancement: enhancement ?? undefined,
    },
  };
}

// ────────────────────────────────────────────────────────────────────────────
// DevOps Agent — extends BaseAgent, handles TaskKind "devops"
// ────────────────────────────────────────────────────────────────────────────

export class DevOpsAgent extends BaseAgent {
  readonly id = "devops-agent" as const;
  readonly info: AgentInfo = {
    id: "devops-agent",
    name: "DevOps Agent",
    description:
      "Generates DevOps and deployment configuration: Docker, docker-compose, nginx, " +
      "CI/CD, and deployment manifests for Vercel, Railway, Render, Fly.io, Coolify, " +
      "and Kubernetes.",
    capabilities: [
      {
        kind: "devops",
        description:
          "Generate Dockerfile, docker-compose, nginx, CI workflows, and deployment manifests",
      },
    ],
    icon: "Server",
    color: "#fb923c",
  };

  protected async execute(
    task: Task,
    signal: AbortSignal,
    onProgress: (p: number, msg: string) => void,
  ): Promise<TaskResult> {
    // 10% — validate
    onProgress(10, "Validating operation and project info");
    const operation = task.input?.operation as DevOpsOperation | undefined;
    const projectInfo = task.input?.projectInfo as ProjectInfo | undefined;
    const provider = task.input?.provider as AIProviderConfig | undefined;

    if (!operation) {
      return this.fail("`operation` is required in task.input");
    }
    if (!projectInfo || !projectInfo.name) {
      return this.fail("`projectInfo.name` is required in task.input");
    }
    if (!OPERATION_META[operation]) {
      return this.fail(`Unsupported operation: ${operation}`);
    }

    if (signal.aborted) throw new Error("Task aborted before generation");

    // 30% — build config
    onProgress(30, `Building ${OPERATION_META[operation].label} for ${projectInfo.name}`);
    const config = await generateDevOpsConfig(operation, projectInfo, provider);

    if (signal.aborted) throw new Error("Task aborted during generation");

    // 70% — finalize content (already done by generateDevOpsConfig)
    onProgress(70, `Finalizing ${config.path}`);

    // 100% — return result
    onProgress(100, `Generated ${config.path} (${config.content.length} bytes)`);

    const artifact: TaskArtifact = {
      kind: "file",
      path: config.path,
      content: config.content,
      language: config.language,
      meta: {
        operation: config.operation,
        label: config.meta.label,
        enhancement: config.meta.enhancement,
        bytes: config.content.length,
      },
    };

    return {
      success: true,
      data: config,
      summary: `Generated ${config.path} for ${projectInfo.name} (operation: ${operation})`,
      artifacts: [artifact],
      metrics: {
        bytes: config.content.length,
        lines: config.content.split("\n").length,
      },
      followUpTasks: this.suggestFollowups(operation, projectInfo),
    };
  }

  /** Suggest logical follow-up tasks based on the operation just performed. */
  private suggestFollowups(
    operation: DevOpsOperation,
    projectInfo: ProjectInfo,
  ): Partial<Task>[] {
    const followUps: Partial<Task>[] = [];

    if (operation === "dockerize") {
      followUps.push({
        kind: "devops",
        title: `Generate docker-compose for ${projectInfo.name}`,
        priority: "medium",
        input: { operation: "compose", projectInfo },
      });
      followUps.push({
        kind: "devops",
        title: `Generate nginx reverse-proxy config`,
        priority: "low",
        input: { operation: "nginx", projectInfo },
      });
    }
    if (operation === "dockerize" || operation === "compose") {
      followUps.push({
        kind: "devops",
        title: `Generate GitHub Actions CI workflow`,
        priority: "high",
        input: { operation: "ci-github-actions", projectInfo },
      });
    }
    if (operation === "kubernetes-manifest") {
      followUps.push({
        kind: "devops",
        title: `Generate Dockerfile for container build`,
        priority: "high",
        input: { operation: "dockerize", projectInfo },
      });
    }

    return followUps;
  }

  private fail(error: string): TaskResult {
    return {
      success: false,
      data: null,
      summary: `DevOps Agent failed: ${error}`,
      artifacts: [],
    };
  }
}

// Singleton
export const devopsAgent = new DevOpsAgent();
